blank_issues_enabled: false
contact_links:
  - name: Project Documentation
    url: https://github.com/contoso/contoso-hve-starter/tree/main/docs
    about: Check our documentation for more information about the project.
